package com.jackson.poc.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import com.jackson.poc.model.Bond;
import com.jackson.poc.model.Cash;
import com.jackson.poc.model.Commodity;
import com.jackson.poc.model.Credit;
import com.jackson.poc.model.CreditDefaultSwap;
import com.jackson.poc.model.CryptoAsset;
import com.jackson.poc.model.CurrencyAmount;
import com.jackson.poc.model.Equity;
import com.jackson.poc.model.FinancialInstrumentIdentification;
import com.jackson.poc.model.FinancialInstrumentType;
import com.jackson.poc.model.FixedDeposit;
import com.jackson.poc.model.Fund;
import com.jackson.poc.model.Future;
import com.jackson.poc.model.FxForward;
import com.jackson.poc.model.FxOption;
import com.jackson.poc.model.FxSwap;
import com.jackson.poc.model.Index;
import com.jackson.poc.model.InterestRate;
import com.jackson.poc.model.InterestRateSwap;
import com.jackson.poc.model.MoneyMarket;
import com.jackson.poc.model.Mortgage;
import com.jackson.poc.model.Option;
import com.jackson.poc.model.OptionStyle;
import com.jackson.poc.model.OptionType;
import com.jackson.poc.model.OtherFinancialInstrument;
import com.jackson.poc.model.Price;
import com.jackson.poc.model.TotalReturnSwap;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.lang.Nullable;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;


@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Bond.class, name = "bond"),
  @JsonSubTypes.Type(value = MoneyMarket.class, name = "callableDeposit"),
  @JsonSubTypes.Type(value = MoneyMarket.class, name = "callableLoan"),
  @JsonSubTypes.Type(value = Cash.class, name = "cash"),
  @JsonSubTypes.Type(value = Commodity.class, name = "commodity"),
  @JsonSubTypes.Type(value = Credit.class, name = "credit"),
  @JsonSubTypes.Type(value = CreditDefaultSwap.class, name = "creditDefaultSwap"),
  @JsonSubTypes.Type(value = CryptoAsset.class, name = "cryptoAsset"),
  @JsonSubTypes.Type(value = Equity.class, name = "equity"),
  @JsonSubTypes.Type(value = FixedDeposit.class, name = "fixedDeposit"),
  @JsonSubTypes.Type(value = MoneyMarket.class, name = "fixedLoan"),
  @JsonSubTypes.Type(value = Fund.class, name = "fund"),
  @JsonSubTypes.Type(value = Future.class, name = "future"),
  @JsonSubTypes.Type(value = FxForward.class, name = "fxForward"),
  @JsonSubTypes.Type(value = FxOption.class, name = "fxOption"),
  @JsonSubTypes.Type(value = FxSwap.class, name = "fxSwap"),
  @JsonSubTypes.Type(value = Index.class, name = "index"),
  @JsonSubTypes.Type(value = InterestRateSwap.class, name = "interestRateSwap"),
  @JsonSubTypes.Type(value = Mortgage.class, name = "mortgage"),
  @JsonSubTypes.Type(value = Option.class, name = "option"),
  @JsonSubTypes.Type(value = OtherFinancialInstrument.class, name = "other"),
  @JsonSubTypes.Type(value = TotalReturnSwap.class, name = "totalReturnSwap"),
  @JsonSubTypes.Type(value = Bond.class, name = "Bond"),
  @JsonSubTypes.Type(value = Cash.class, name = "Cash"),
  @JsonSubTypes.Type(value = Commodity.class, name = "Commodity"),
  @JsonSubTypes.Type(value = Credit.class, name = "Credit"),
  @JsonSubTypes.Type(value = CreditDefaultSwap.class, name = "CreditDefaultSwap"),
  @JsonSubTypes.Type(value = CryptoAsset.class, name = "CryptoAsset"),
  @JsonSubTypes.Type(value = Equity.class, name = "Equity"),
  @JsonSubTypes.Type(value = FixedDeposit.class, name = "FixedDeposit"),
  @JsonSubTypes.Type(value = Fund.class, name = "Fund"),
  @JsonSubTypes.Type(value = Future.class, name = "Future"),
  @JsonSubTypes.Type(value = FxForward.class, name = "FxForward"),
  @JsonSubTypes.Type(value = FxOption.class, name = "FxOption"),
  @JsonSubTypes.Type(value = FxSwap.class, name = "FxSwap"),
  @JsonSubTypes.Type(value = Index.class, name = "Index"),
  @JsonSubTypes.Type(value = InterestRateSwap.class, name = "InterestRateSwap"),
  @JsonSubTypes.Type(value = MoneyMarket.class, name = "MoneyMarket"),
  @JsonSubTypes.Type(value = Mortgage.class, name = "Mortgage"),
  @JsonSubTypes.Type(value = Option.class, name = "Option"),
  @JsonSubTypes.Type(value = OtherFinancialInstrument.class, name = "OtherFinancialInstrument"),
  @JsonSubTypes.Type(value = TotalReturnSwap.class, name = "TotalReturnSwap")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-11T20:52:16.917303731+02:00[Europe/Zurich]", comments = "Generator version: 7.12.0")
public interface FinancialInstrument {
    public FinancialInstrumentType getType();
}
