/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.jackson.poc.api;

import com.jackson.poc.model.CommonErrorResponse;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.LocalDate;
import com.jackson.poc.model.ValuatedPosition;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-11T20:28:41.461831241+02:00[Europe/Zurich]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "positions", description = "Position operations.")
public interface AccountsApi {

    default AccountsApiDelegate getDelegate() {
        return new AccountsApiDelegate() {};
    }

    /**
     * GET /accounts/{accountId}/positions : Returns the positions for a specific account
     * Returns all positions for a specific account. Paging is done based on the position object, i.e. if limit is set to 1, then 1 position will be returned per page. 
     *
     * @param accountId Account ID parameter. (required)
     * @param date A date value. (required)
     * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. (required)
     * @param endOfDayIndicator Indicates if the resources (positions &amp; transactions) have been confirmed by the end-of-day (eod) processing. - If the parameter is not set, all resources will be delivered. - If the parameter is set to true, only resources with with the particular property set to true will be delivered. - If the parameter is set to false, only resources with with the particular property set to false will be delivered.  (optional)
     * @param cursor An opaque string value used for pagination. (optional)
     * @param limit Maximum number of items to return. (optional)
     * @return Position List (status code 200)
     *         or Bad Request - The server cannot or will not process the request due to something that is perceived to be a client error as malformed request syntax.  (status code 400)
     *         or Unauthorized - The request has not been applied because it lacks valid authentication credentials for the target resource. (status code 401)
     *         or Forbidden - The server understood the request but refuses to authorize it. (status code 403)
     *         or Not Found - The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.  (status code 404)
     *         or Method Not Allowed - The method received in the request-line is known by the origin server but not supported by the target resource.  (status code 405)
     *         or Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request. (status code 500)
     *         or Not Implemented - The server does not support the functionality required to fulfill the request. (status code 501)
     *         or Service Unavailable - The server is currently unable to handle the request due to a temporary overload or scheduled maintenance. (status code 503)
     */
    @Operation(
        operationId = "getAccountPositionByAccountId",
        summary = "Returns the positions for a specific account",
        description = "Returns all positions for a specific account. Paging is done based on the position object, i.e. if limit is set to 1, then 1 position will be returned per page. ",
        tags = { "positions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Position List", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ValuatedPosition.class))),
                @Content(mediaType = "application/problem+json", array = @ArraySchema(schema = @Schema(implementation = ValuatedPosition.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request - The server cannot or will not process the request due to something that is perceived to be a client error as malformed request syntax. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - The request has not been applied because it lacks valid authentication credentials for the target resource.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden - The server understood the request but refuses to authorize it.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found - The origin server did not find a current representation for the target resource or is not willing to disclose that one exists. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not Allowed - The method received in the request-line is known by the origin server but not supported by the target resource. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "501", description = "Not Implemented - The server does not support the functionality required to fulfill the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable - The server is currently unable to handle the request due to a temporary overload or scheduled maintenance.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts/{accountId}/positions",
        produces = { "application/json", "application/problem+json" }
    )
    
    default ResponseEntity<List<ValuatedPosition>> getAccountPositionByAccountId(
        @Size(max = 128) @Parameter(name = "accountId", description = "Account ID parameter.", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @NotNull @Parameter(name = "date", description = "A date value.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "date", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date,
        @NotNull @Parameter(name = "X-Correlation-ID", description = "Unique ID (defined by the caller) which will be reflected back in the response.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Correlation-ID", required = true) String xCorrelationID,
        @Parameter(name = "end_of_day_indicator", description = "Indicates if the resources (positions & transactions) have been confirmed by the end-of-day (eod) processing. - If the parameter is not set, all resources will be delivered. - If the parameter is set to true, only resources with with the particular property set to true will be delivered. - If the parameter is set to false, only resources with with the particular property set to false will be delivered. ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "end_of_day_indicator", required = false) Boolean endOfDayIndicator,
        @Parameter(name = "cursor", description = "An opaque string value used for pagination.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cursor", required = false) String cursor,
        @Min(1) @Parameter(name = "limit", description = "Maximum number of items to return.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false) Integer limit
    ) {
        return getDelegate().getAccountPositionByAccountId(accountId, date, xCorrelationID, endOfDayIndicator, cursor, limit);
    }


    /**
     * GET /accounts/{accountId}/positions/{positionId} : Returns a positions by id for a specific account
     * Returns a positions for a specific account.
     *
     * @param accountId Account ID parameter. (required)
     * @param positionId Position ID parameter. (required)
     * @param date A date value. (required)
     * @param xCorrelationID Unique ID (defined by the caller) which will be reflected back in the response. (required)
     * @param endOfDayIndicator Indicates if the resources (positions &amp; transactions) have been confirmed by the end-of-day (eod) processing. - If the parameter is not set, all resources will be delivered. - If the parameter is set to true, only resources with with the particular property set to true will be delivered. - If the parameter is set to false, only resources with with the particular property set to false will be delivered.  (optional)
     * @return Position (status code 200)
     *         or Bad Request - The server cannot or will not process the request due to something that is perceived to be a client error as malformed request syntax.  (status code 400)
     *         or Unauthorized - The request has not been applied because it lacks valid authentication credentials for the target resource. (status code 401)
     *         or Forbidden - The server understood the request but refuses to authorize it. (status code 403)
     *         or Not Found - The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.  (status code 404)
     *         or Method Not Allowed - The method received in the request-line is known by the origin server but not supported by the target resource.  (status code 405)
     *         or Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request. (status code 500)
     *         or Not Implemented - The server does not support the functionality required to fulfill the request. (status code 501)
     *         or Service Unavailable - The server is currently unable to handle the request due to a temporary overload or scheduled maintenance. (status code 503)
     */
    @Operation(
        operationId = "getAccountPositionById",
        summary = "Returns a positions by id for a specific account",
        description = "Returns a positions for a specific account.",
        tags = { "positions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Position", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValuatedPosition.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ValuatedPosition.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request - The server cannot or will not process the request due to something that is perceived to be a client error as malformed request syntax. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - The request has not been applied because it lacks valid authentication credentials for the target resource.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden - The server understood the request but refuses to authorize it.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found - The origin server did not find a current representation for the target resource or is not willing to disclose that one exists. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not Allowed - The method received in the request-line is known by the origin server but not supported by the target resource. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error - The server encountered an unexpected condition that prevented it from fulfilling the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "501", description = "Not Implemented - The server does not support the functionality required to fulfill the request.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable - The server is currently unable to handle the request due to a temporary overload or scheduled maintenance.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommonErrorResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = CommonErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts/{accountId}/positions/{positionId}",
        produces = { "application/json", "application/problem+json" }
    )
    
    default ResponseEntity<ValuatedPosition> getAccountPositionById(
        @Size(max = 128) @Parameter(name = "accountId", description = "Account ID parameter.", required = true, in = ParameterIn.PATH) @PathVariable("accountId") String accountId,
        @Size(max = 128) @Parameter(name = "positionId", description = "Position ID parameter.", required = true, in = ParameterIn.PATH) @PathVariable("positionId") String positionId,
        @NotNull @Parameter(name = "date", description = "A date value.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "date", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date,
        @NotNull @Parameter(name = "X-Correlation-ID", description = "Unique ID (defined by the caller) which will be reflected back in the response.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Correlation-ID", required = true) String xCorrelationID,
        @Parameter(name = "end_of_day_indicator", description = "Indicates if the resources (positions & transactions) have been confirmed by the end-of-day (eod) processing. - If the parameter is not set, all resources will be delivered. - If the parameter is set to true, only resources with with the particular property set to true will be delivered. - If the parameter is set to false, only resources with with the particular property set to false will be delivered. ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "end_of_day_indicator", required = false) Boolean endOfDayIndicator
    ) {
        return getDelegate().getAccountPositionById(accountId, positionId, date, xCorrelationID, endOfDayIndicator);
    }

}
