openapi: 3.0.0
info:
  version: 3.0.0-draft
  title: Order Placement API
  description: This API is used to place orders and check on the order status.
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Your server url
    url: https://www.openwealth.ch
security: []
tags:
  - name: account
    description: Account operations.
  - name: order
    description: Order operations.
  - name: execution
    description: Execution operations.
  - name: order-status
    description: Order status operations.
  - name: event-subscription
    description: Event notification subscription operations.
  - name: event-notification
    description: Event notification operations.
externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch
paths:
  /accounts:
    $ref: paths/accounts.yaml
  /orders:
    $ref: paths/orders.yaml
  /orders/{orderId}:
    $ref: paths/orders_{orderId}.yaml
  /orders/{orderId}/action/cancel:
    $ref: paths/orders_{orderId}_action_cancel.yaml
  /orders/{orderId}/executions:
    $ref: paths/orders_{orderId}_executions.yaml
  /orders/{orderId}/executions/{executionId}:
    $ref: paths/orders_{orderId}_executions_{executionId}.yaml
  /orders/{orderId}/statuses:
    $ref: paths/orders_{orderId}_statuses.yaml
  /event-subscriptions:
    $ref: paths/event-subscriptions.yaml
  /event-subscriptions/{eventSubscriptionId}:
    $ref: paths/event-subscriptions_{eventSubscriptionId}.yaml
  /event-subscriptions/{eventSubscriptionId}/event-notifications:
    $ref: paths/event-subscriptions_{eventSubscriptionId}_event-notifications.yaml
