openapi: 3.0.0
info:
  version: 2.2.1
  title: OpenWealth Order Placement Event Notification API - TPP Endpoint
  description: API for Receiving Event Notification for OpenWealth APIs.
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - description: Your server url
    url: https://www.openwealth.ch

externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch

tags:
  - name: event-notification
    description: Order event notifications.

security: []

paths:
  /event-notifications:
    post:
      tags:
        - event-notification
      summary: Push notification towards TPP
      description: Push notficiations for subscribed event notifications.
      operationId: postEventNotification
      parameters:
        - $ref: '#/components/parameters/correlation_in_header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/schemas/notificationOrderPlacement.yaml'

      responses:
        '202':
          description: Notification accepted.
          headers:
            X-Correlation-ID:
              $ref: '../generics/V2/components/headers/X-Correlation-ID.yaml'

        '400':
          $ref: '../generics/V2/components/responses/400.yaml'
        '500':
          $ref: '../generics/V2/components/responses/500.yaml'

components:
  parameters:
    correlation_in_header:
      in: header
      name: X-Correlation-ID
      description: Unique ID (defined by the caller) which will be reflected back in the response.
      required: true
      schema:
        type: string
