openapi: 3.0.0
info:
  version: 3.0.0
  title: OpenWealth trading event notification API - TPP Endpoint
  description: API for receiving event notification for OpenWealth APIs.
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - description: The TPP webhook server url.
    url: https://www.tpp-url.ch

externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch

tags:
  - name: event-notification
    description: Order event notifications.

security: []

paths:
  /event-notifications:
    post:
      tags:
        - event-notification
      summary: Push notification towards TPP
      description: Push notification for subscribed event notifications.
      operationId: pushEventNotification
      parameters:
        - $ref: ../generics/components/parameters/correlation_id.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/schemas/EventNotification.yaml'

      responses:
        '202':
          description: Notification accepted.
          headers:
            Correlation-Id:
              $ref: '../generics/components/headers/Correlation-Id.yaml'

        '400':
          $ref: '../generics/components/responses/400.yaml'
        '500':
          $ref: '../generics/components/responses/500.yaml'
components:
  schemas: {}
  responses: {}
  parameters: {}
  headers: {}
  securitySchemes: {}
