openapi: 3.0.0
info:
  version: 3.0.0-draft
  title: Customer API
  description: |
    This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems
    and CRMs). It facilitates the connection of CRMs to custody banks to automate customer onboarding and lifecycle management (Static Data
    KYC & Documents). It enables the user to create, modify and consume customer data at/from custody banks.
    This version of the API is focused solely on natural persons. The management of companies, complex structures as well as products is
    currently not part of the scope of this API version.
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Your Server URL.
    url: https://api.openwealth.ch
externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch
security: []
paths:
  /customers:
    $ref: paths/customers.yaml
  /customers/{customerId}:
    $ref: paths/customers_{customerId}.yaml
  /customers/{customerId}/mandates:
    $ref: paths/customers_{customerId}_mandates.yaml
  /customers/{customerId}/mandates/{mandateId}:
    $ref: paths/customers_{customerId}_mandates_{mandateId}.yaml
  /persons:
    $ref: paths/persons.yaml
  /persons/{personId}:
    $ref: paths/persons_{personId}.yaml

components:
  schemas: {}
  responses: {}
  parameters: {}
  headers: {}
  securitySchemes: {}
