openapi: 3.0.0
info:
  version: 3.2.0
  title: Custody Services
  description: |
    This API is part of the OpenWealth APIs for the connectivity between custody banks and WealthTechs (e.g. Portfolio Management Systems).
    This API allows the user to receive data from custody banks regarding accounts and positions. The API is designed to be used for either
    update end of day data batches or single near-realtime account/position information. Furthermore, this API allows the user to receive
    data from custody banks regarding transactions.
  contact:
    email: openwealth@synpulse.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Your Server URL.
    url: https://api.openwealth.ch
externalDocs:
  description: Find out more about OpenWealth API specifications.
  url: https://openwealth.ch
tags:
  - name: accounts
    description: Accounts operations.
  - name: customers
    description: Customer operations.
  - name: positions
    description: Position operations.
  - name: transactions
    description: Transaction operations.
security: []
paths:
  /customers:
    $ref: paths/customers.yaml
  /customers/{customerId}:
    $ref: paths/customers_{customerId}.yaml
  /customers/{customerId}/accounts:
    $ref: paths/customers_{customerId}_accounts.yaml
  /customers/{customerId}/accounts/{accountId}:
    $ref: paths/customers_{customerId}_accounts_{accountId}.yaml
  /customers/{customerId}/positions:
    $ref: paths/customers_{customerId}_positions.yaml
  /customers/{customerId}/positions/{positionId}:
    $ref: paths/customers_{customerId}_positions_{positionId}.yaml
  /accounts/{accountId}/positions:
    $ref: paths/accounts_{accountId}_positions.yaml
  /accounts/{accountId}/positions/{positionId}:
    $ref: paths/accounts_{accountId}_positions_{positionId}.yaml
  /customers/{customerId}/transactions:
    $ref: paths/customers_{customerId}_transactions.yaml
  /customers/{customerId}/transactions/{transactionId}:
    $ref: paths/customers_{customerId}_transactions_{transactionId}.yaml
components:
  schemas: {}
  responses: {}
  parameters: {}
  headers: {}
  securitySchemes: {}
