openapi: 3.0.3
info:
  description: |
    This is the specification of the documents API plugin. It is intended to be
    integrated into existing business-apis.
  version: 1.0.0-draft
  title: Documents API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: openwealth@synpulse.com
servers:
  - description: Your Server URL.
    url: https://example.org
security: []
paths:
  /cases:
    $ref: paths/cases.yaml
  /cases/{caseId}:
    $ref: paths/cases_{caseId}.yaml
  /cases/{caseId}/actions/{action}:
    $ref: paths/cases_{caseId}_actions_{action}.yaml
  /cases/{caseId}/documents:
    $ref: paths/cases_{caseId}_documents.yaml
  /cases/{caseId}/documents/{documentId}:
    $ref: paths/cases_{caseId}_documents_{documentId}.yaml
  /cases/{caseId}/documents/{documentId}/content:
    $ref: paths/cases_{caseId}_documents_{documentId}_content.yaml
