name: Pull Request Checks
# description: Check specifications for SFTI's openapi rules.
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled] # Trigger on PR actions like opening or updating a PR
    branches:
      - main # Only triggers for pull requests targeting the main branch

permissions:
  contents: write
  pull-requests: write

jobs:
  lint_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint APIs
        run: |
          api=${{ needs.get_api_from_label.outputs.API }}
          find . -type f -name "API.yaml" -exec redocly lint {} --config=.github/redocly.yaml --format=stylish \;

  lint_api_with_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check if example branch exists and checkout
        run: |
          FIXED_BRANCH="spec-including-examples"

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if remote branch exists
          if git ls-remote --exit-code --heads origin "$FIXED_BRANCH"; then
            echo "Branch '$FIXED_BRANCH' exists. Checking it out..."

            # Fetch the fixed branch from origin
            git fetch origin $FIXED_BRANCH

            # Rebase it the PR source branch onto fixe brnch containing examples
            git rebase origin/$FIXED_BRANCH || {
              echo "Rebase failed due to conflicts."
              git rebase --abort
              exit 1
            }
          else
            echo "Branch '$FIXED_BRANCH' does not exist. Failed linting examples."
            exit 1
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint API
        run: |
          find . -type f -name "API.yaml" -exec redocly lint {} --config=.github/redocly.yaml --format=stylish \;
